---
title: "Covid ShinyApp"
author: "Makivic Bojan, MMSc"
runtime: shiny
---

```{r setup}
knitr::opts_chunk$set(echo = TRUE)
```

## Libraries

```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)
library(stringr)
library(rebus)
library(lubridate)
library(shiny)
library(shinythemes)
library(shinyWidgets)
library(shinydashboard)
library(countrycode)
library(plyr)
library(ggrepel)
library(rsconnect)
library(ggplot2)
library(dplyr)
library(plotly)
library(flexdashboard)
library(maps)
library(png)
library(sunburstR)
library(rmapshaper)
library(knitr)
library(rvest)
library(sf)
library(raster)
library(spData)
library(tmap)
library(rgdal)
library(highcharter)
library(xts)
library(broom)
library(rAmCharts)
library(GGally)
```

## DATA PREPARATION

```{r echo=TRUE, message=FALSE, warning=FALSE}
# Scraping data

url <- read_html("https://www.worldometers.info/coronavirus/")

# FIrST DATAFRAME

df <- url %>%
  html_nodes("table") %>%
  .[[1]] %>%
  html_table()

df <- df[-c(1, 15, 17, 18, 19)] # remove last three colums

df <- df %>% mutate_all(funs(gsub("[[:punct:]]", "", .))) # remove special characters from dataframe

i <- c(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13,15,16,17) # return columns from 3 to 12 as integer
df[, i] <-
  apply(df[, i], 2, function(x) {
    as.integer(as.character(x))
  })

df[is.na(df)] <- 0

names(df)[1] <- "Country"
names(df)[9:13] <- c("Serious", "Cases_1M", "Deaths_1M", "Total_Tests", "Tests_1M")

no <-
  c(
    "Diamond Princess",
    "MS Zaandam",
    "St Barth",
    "Total",
    "World",
    "All",
    "North America",
    "South America",
    "Asia",
    "Africa",
    "Oceania",
    "Europe",
    ""
  )
dfnoco <- filter(df, !df$Country %in% no)
df <- filter(df, !df$Country %in% no[no == "Total"])
dfnoco$countryCode <-
  countrycode(dfnoco$Country, origin = "country.name", destination = "iso3c")

if(is.numeric(dfnoco)){dfnoco[is.na(dfnoco)]<-0} # converting NA values into O

old <- c(
  "CAR",
  "Czechia",
  "GuineaBissau",
  "Vatican City",
  "S Korea",
  "UAE",
  "UK",
  "USA",
  "Congo",
  "DRC",
  "Saint Kitts and Nevis"
)
new <- c(
  "Central African Republic",
  "Czech Republic",
  "Guinea-Bissau",
  "Vatican",
  "South Korea",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Republic of the Congo",
  "DR Congo",
  "Saint Kittis and Nevis"
)

for (i in 1:length(old)) {
  dfnoco$Country <- gsub(old[i], new[i], dfnoco$Country)
}

# for Regression
dfnoco2 <- filter(df, !df$Country %in% no)
dfnoco2$countryCode <-
  countrycode(dfnoco2$Country, origin = "country.name", destination = "iso3c")

if(is.numeric(dfnoco2)){dfnoco2[is.na(dfnoco2)]<-0} # converting NA values into O
for (i in 1:length(old)) {
  dfnoco2$Country <- gsub(old[i], new[i], dfnoco2$Country)
}

names(dfnoco)[2:8] <- c("Total cases", "New cases", "Total deaths", "New deaths", "Total recovered","New recovered", "Active cases")
names(dfnoco)[10:13] <- c("Cases/1M", "Deaths/1M", "Total tests", "Tests/1M")


# SECOND DATAFRAME

url2 <-
  read_html("https://www.worldometers.info/coronavirus/worldwide-graphs/#case-timeline")

df_url2 <- url2 %>%
  html_nodes("table") %>%
  .[[1]] %>%
  html_table()
df_url2 <- df_url2[nrow(df_url2):1, ]
names(df_url2)[2:4] <-
  c(
    "Total deaths cumulative",
    "Daily deaths",
    "% increase in daily deaths"
  )

df_url2 <- df_url2 %>% mutate_all(funs(gsub("[[:punct:]]", "", .)))
invisible(format(df_url2, justify = "left"))
df_url2[, 2:4] <-
  apply(df_url2[, 2:4], 2, function(x) {
    as.integer(as.character(x))
  })

# This has to be done on order taht "highchart" works
df_url2$Date <- mdy(df_url2$Date) # convert the date to m/d/y
df_url2$Date <- as.Date(df_url2$Date) # convert to class Date
df_url2 <- xts(df_url2[2:4], order.by = as.POSIXct(df_url2$Date)) # Order the data frame by date column (date column has to be changed to type as.POSIXct in order to work)

# df_url2[is.na(df_url2)] <- 0

# THIRD DATAFRAME

url3 <-
  read_html("https://www.worldometers.info/world-population/population-by-country/") # Population
df_url3 <- url3 %>%
  html_nodes("table") %>%
  .[[1]] %>%
  html_table()
df_url3 <-
  df_url3 %>% mutate_all(funs(gsub("[[:punct:]]", "", .))) # clean special signs except letters, numbers, . and -
df_url3 <-
  df_url3[-c(0, 1, 4, 5, 8, 9)] # drop colums by index number
names(df_url3)[1:6] <-
  c(
    "Country",
    "Population",
    "Pop_density",
    "Land_area",
    "Median_age",
    "Urban_pop"
  )

df_url3[, 2:6] <- # return columns from 2 to 6 as integer
  apply(df_url3[, 2:6], 2, function(x) {
    as.integer(as.character(x))
  })
df_url3$countryCode <-
  countrycode(df_url3$Country, origin = "country.name", destination = "iso3c")
if(is.numeric(df_url3)){df_url3[is.na(df_url3)] <- 0}
df_url3$Country <- gsub("DR Congo", "DR Kongo", df_url3$Country)

old <- c(
  "GuineaBissau",
  "Czech Republic Czechia",
  "Holy See",
  "Saint Kittis  Nevis",
  "Saint Pierre  Miquelon",
  "Sao Tome  Principe",
  "St Vincent  Grenadines",
  "State of Palestine",
  "Wallis  Futuna",
  "Côte dIvoire",
  "Congo",
  "DR Kongo"
)
new <- c(
  "Guinea-Bissau",
  "Czech Republic",
  "Vatican",
  "Saint Kittis and Nevis",
  "Saint Pierre Miquelon",
  "Sao Tome and Principe",
  "St Vincent Grenadines",
  "Palestine",
  "Wallis and Futuna",
  "Ivory Coast",
  "Republic of the Congo",
  "DR Congo"
)

for (i in 1:length(old)) {
  df_url3$Country <- gsub(old[i], new[i], df_url3$Country)
}

# Data frame 4th

k <- c(2, 9, 10)
df_4 <- world[, k]
names(df_4)[1] <- c("Country")
df_4[is.na(df_4)] <- 0

old <- c(
  "eSwatini",
  "Dem. Rep. Korea",
  "Lao PDR",
  "Macedonia",
  "The Gambia",
  "Timor-Leste",
  "Russian Federation",
  "Republic of Korea",
  "Democratic Republic of the Congo",
  "Côte d'Ivoire"
)
new <- c(
  "Eswatini",
  "North Korea",
  "Laos",
  "North Macedonia",
  "Gambia",
  "TimorLeste",
  "Russia",
  "South Korea",
  "DR Congo",
  "Ivory Coast"
)

for (i in 1:length(old)) {
  df_4$Country <- gsub(old[i], new[i], df_4$Country)
}

# Vaccination

vacc <- read.csv("https://raw.githubusercontent.com/owid/covid-19-data/master/public/data/vaccinations/vaccinations.csv")
names(vacc)[1] <- "Country"
vacc <- vacc[c(3, 2, 1, 4, 5, 6, 7, 8, 9, 10, 11, 12)]

vacc$date <- format(as.Date(vacc$date), "%d/%m/%y")
vacc$date <- strptime(as.character(vacc$date), "%d/%m/%y")

ZoomButton <- data.frame(
  Unit = c("DD", "DD", "MAX"), multiple = c(7, 14, 1),
  label = c("7 days", "14 days", "MAX")
)

names(vacc)[2] <- "countryCode"

# Join data frames
join <-
  merge(dfnoco, df_4, by = "Country", all = TRUE) # merge df and df_url3 dataframes in one
join <- join[c(-15)]

join_r <- # for Regression
  merge(dfnoco2, df_4, by = "Country", all = TRUE) # merge df and df_url3 dataframes in one
join_r <- join_r[c(-15)]

join2 <-
  merge(join[-c(17)], df_url3, by = "Country", all = TRUE)
names(join2)[13] <- c("Tests_1M")
join2[, c(2:13, 15, 16)] <-
  apply(join2[, c(2:13, 15, 16)], 2, function(x) {
    as.integer(as.numeric(x))
  })

join3 <- # for Regression
  merge(join_r[-c(17,20)], df_url3, by = "Country", all = TRUE)
names(join3)[c(13,15,16)] <- c("Tests_1M", "New_deaths_1M", "Active_cases_1M")
join3[, c(2:13, 15, 16)] <-
  apply(join3[, c(2:13, 15, 16)], 2, function(x) {
    as.integer(as.numeric(x))
  })

join3[is.na(join3)] <- 0 # for Regression

names(join2)[2:8] <- c("Total cases", "New cases", "Total deaths", "New deaths", "Total recovered","New recovered", "Active cases")
names(join2)[10:13] <- c("Cases/1M", "Deaths/1M", "Total tests", "Tests/1M")
names(join2)[15:18] <- c("New deaths/1M", "Active cases/1M", "Life expectancy", "GDP per capita")
names(join2)[21:24] <- c("Population density","Land area", "Median age", "Urban population")

join2[is.na(join2)] <- 0

# Map view 2

fName <- "TM_WORLD_BORDERS-0.3.shp"

states <- st_read(dsn = fName)
names(states)[3] <- "countryCode"

data_full_states <- states %>%
  left_join(dfnoco, by = "countryCode")

data_full_states <- data_full_states %>%
  left_join(df_url3, by = "countryCode")
  
vaxx_full_geo <- states %>%
  left_join(vacc, by = "countryCode")

vaxx_full_geo <-vaxx_full_geo %>%  filter(date <= today() & date >= today() - days(100))

vaxx_full_geo <- vaxx_full_geo  %>% group_by(countryCode) %>%  filter(people_vaccinated_per_hundred==max(people_vaccinated_per_hundred, na.rm=T))
```

## DF for Box plot
```{r}
df_con <- dfnoco[8:219, ]
df_con$"Total tests" <- as.numeric(df_con$"Total tests")
df_con$"Tests/1M" <- as.numeric(df_con$"Tests/1M")
```


## Function to plot regression with summary data
```{r echo=TRUE}
ggplotRegression <- function(fit) {
  require(ggplot2)
  ggplot(fit$model, aes_string(
    # colour= names(fit$model)[4],
    # fill = names(fit$model)[5],
    y = names(fit$model)[1],
    x = names(fit$model)[2],
    s = names(fit$model)[4],
    label = names(fit$model)[3]
  )) +
    geom_point(na.rm = TRUE) +
    labs(x = paste(names(fit$model)[2]), y = paste(names(fit$model)[1])) +
    stat_smooth(method = "lm", se = TRUE) +
    labs(title = paste(
      "adjusted R2 =",
      signif(summary(fit)$adj.r.squared, 2),
      "  |  n :",
      length(fit[["xlevels"]][["Country"]]),
      "  |  p value:",
      signif(glance(fit)$p.value, 4)
      # " Slope =",
      # signif(fit$coef[[2]], 2)
    ))
}
```


## Mapping option optimization

```{r Mapping option optimization, echo=TRUE}
Co <- as.list(df$TotalCases)
names(Co) <- df$Country

country_line_color <- list(color = toRGB("gray"), width = 1.2)
map_options <- list(
  showframe = FALSE,
  showcoastlines = FALSE,
  projection = list(type = "Mercator")
)
```

# Dashboard page title
```
#title <- tags$a("SARS-CoV 2", tags$img(src = "Coronavirus.png", height = "30", width = "30"), style = "color: white;")
```

## Define UI 
```{r, echo=TRUE}
ui <- shinyUI(dashboardPage(
  dashboardHeader(title = "SARS-CoV 2", tags$li(
    tags$a(
      href = "https://github.com/BojanMakivic",
      tags$img(height = "30px", title = "View on Github", src = "PNG/GitHub-Mark-64px.png"),
      style = "padding-top:10px; padding-bottom:10px;"
    ),
    class = "dropdown"
  )),
  dashboardSidebar(
    sidebarMenu(
      menuItem(
        "Dashboard",
        tabName = "MainTab",
        icon = icon("dashboard")
      ),
      menuItem(
        "Bar chart",
        tabName = "NewCases",
        icon = icon("bar-chart-o")
      ),
      menuItem(
        "Map view 1",
        tabName = "TotalCases",
        icon = icon("chart-line")
      ),
      menuItem(
        "Map view 2",
        tabName = "TotalCases2",
        icon = icon("chart-line")
      ),
      menuItem("Box plot",
        tabName = "Boxplot", icon =
          icon("box")
      ),
      menuItem("SunBurst Graph", tabName = "SunBurst", icon = icon("sun")),
      menuSubItem("Daily deaths",
        tabName = "DailyDeaths", icon =
          icon("skull")
      ),
      menuItem("Vaccination", tabName = "vacc", icon = icon("syringe"), badgeLabel = "new", badgeColor = "green"),
      menuItem(
        "Regression analysis",
        tabName = "Dens",
        icon = icon("bar-chart-o")
      )
    )
  ),
  dashboardBody(
    tabItems(
      tabItem(
        tabName = "MainTab",
        fluidPage(
          theme = shinytheme("flatly"),
          fluidRow(
            column(12, titlePanel("PLEASE CHOOSE THE DASHBOARD FROM SIDEBAR MENU"), align = "center")
          ),
          fluidRow(column(12, img(src = "Coronavirus.png"), align = "center")),
          fluidRow(column(6, titlePanel(h3("Credit: Bojan Makivic, MMMSc")), style = "height:10px"))
        )
      ),
      tabItem(
        tabName = "NewCases",
        fluidPage(
          fluidRow(column(12,
            selectInput("first", "Select parameter:",
              choices = colnames(dfnoco[c(2:13)])
            ),
            style = "height:120px"
          )),
          fluidRow(column(
            12,
            highchartOutput("plotDist", height = "500px")
          ))
        )
      ),
      tabItem(
        tabName = "TotalCases",
        fluidPage(
          fluidRow(
            column(6,
              theme = shinytheme("cerulean"),
              infoBox("Total cases world wide", df$TotalCases[df$Country == "World"], width = "100%"),
              icon = icon("chart-line"),
              infoBoxOutput("infoBox")
            ),
            column(
              3,
              selectInput("var", "Select continent:",
                choices =
                  Co[df$Country[1:6]]
              )
            ),
            column(3, gaugeOutput("table"), style = "height:20px")
          ),
          fluidRow(
            column(
              6,
              selectInput("par_M", "Select variable:", choices = colnames(join2[c(2:13, 15:16, 18:22)]))
            )
          ),
          fluidRow(column(
            12,
            plotlyOutput("geo", width = "100%", height = "600px")
          ))
        )
      ),
      tabItem(
        tabName = "TotalCases2",
        fluidPage(
          tmapOutput("geo2", width = "100%", height = 800)
        )
      ),
      tabItem(
        tabName = "Boxplot",
        fluidPage(
          fluidRow(
            column(12,
              align = "center",
              icon = icon("box"),
              titlePanel(h1("Boxplot"))
            )
          ),
          fluidRow(column(
            3,
            selectInput("Box_par", "Select variable:", choices = colnames(dfnoco[c(2:13)]))
          )),
          fluidPage(
            column(12, highchartOutput("Boxplot1", height = "500px"))
          )
        )
      ),
      tabItem(
        tabName = "SunBurst",
        fluidPage(
          fluidRow(
            column(
              3,
              h5(
                "Hover with the mouse coursor over the specific parameter, e.g. active cases,
                                                         and click on it in order to reveal an additional information."
              )
            ),
            column(6, offset = 2, titlePanel(h1("SunBurst graph")))
          ),
          fluidRow(column(
            3,
            selectInput("var1", "Select country:",
              choices =
                join2$Country
            )
          )),
          fluidPage(
            plotlyOutput("SunBurst", width = "100%", height = "800px")
          )
        )
      ),
      tabItem(
        tabName = "DailyDeaths",
        fluidPage(fluidRow(
          column(
            12,
            titlePanel(h1("Daily deaths by Covid-19", align = "center"))
          ),
          column(3, selectInput("var_dd", "Select variable:", choices = colnames(df_url2[c(0:3)]))),
          fluidPage(highchartOutput("plotDD"), width = "100%")
        ))
      ),
      tabItem(
        tabName = "vacc",
        navbarPage(
          "Vaccination",
          tabPanel(
            "Metrics",
            fluidPage(
              fluidRow(
                column(3, selectInput("vacc_par", "Select country:",
                  choices = c(World = "World", vacc$Country), selected = TRUE
                )),
                column(
                  3,
                  switchInput("fill", "Fill", value = FALSE)
                )
              ),
              fluidRow(amChartsOutput("vaxx", height = "500px"))
            )
          ),
          tabPanel(
            "Map visual",
            fluidPage(
              fluidRow(
                column(3, selectInput("vaxx_par", "Select metric:",
                  choices = colnames(vaxx_full_geo[c(14:22)]), selected = TRUE
                )),
                fluidRow(tmapOutput("geo3", width = "100%", height = 800))
              )
            )
          )
        )
      ),
      tabItem(
        tabName = "Dens",
        navbarPage(
          "Linear regression analysis",
          tabPanel(
            "LR Plot",
            fluidPage(
              fluidRow(
                column(
                  2,
                  numericInput("num",
                    "x-axis cut off:",
                    max = 900000000,
                    min = 0,
                    value = 300000000
                  ),
                  numericInput(
                    "num2",
                    "y-axis cut off:",
                    max(90000000),
                    min = 1,
                    value = 300000000
                  )
                ),
                column(2,
                  offset = 1,
                  selectInput("con", "Select continent:",
                    choices =
                      join3$Continent[join3$Continent != "0"]
                  ),
                  selectInput("response", "Select response variable:", choices = colnames(join3[c(3:13, 15:16, 18:22, 2)]))
                ),
                column(1,
                  offset = 1,
                  checkboxInput("LogX", "Log response", FALSE)
                ),
                column(2,
                  offset = 1,
                  selectInput("paraM1", "Select predictor variable:", choices = colnames(join3[c(2:13, 15:16, 18:22)]), selected = "TotalDeaths"),
                  selectInput("paraM2", "Select 2nd predictor variable:", choices = colnames(join3[c(2:13, 15:16, 18:22)]))
                ),
                column(1,
                  offset = 1,
                  checkboxInput("LogY1", "Log 1st", FALSE),
                  checkboxInput("LogY2", "Log 2nd", FALSE)
                ),
                fluidRow(column(12,
                  plotlyOutput("plotDens"),
                  style = "height:10px"
                )),
              )
            )
          ),
          tabPanel(
            "Correlation matrix",
            fluidPage(
              plotOutput("corrmatrix", height = 520)
            )
          )
        )
      )
    )
  )
))
```


## Server

```{r eruptions, echo=TRUE}
server <- function(input, output, session) {
  output$plotDist <- renderHighchart({
    chart <- highchart() %>%
      hc_chart(type = "column") %>%
      hc_title(text = "SARS-CoV-2 Indices by country") %>%
      hc_xAxis(categories = dfnoco$Country) %>%
      hc_yAxis(title = list(text = "Cases"))
    hc <- chart %>%
      hc_add_series(pointWidth = 8, yAxis = 0, name = paste(input$first), data = sort(dfnoco[[input$first]], decreasing = TRUE)) %>%
      hc_plotOptions(column = list(dataLabels = list(enabled = TRUE)))
  })

  output$Boxplot1 <- renderHighchart({
    dat <- data_to_boxplot(df_con, get(input$Box_par), Continent, add_outliers = FALSE, name = paste(input$Box_par))

    highchart() %>%
      hc_xAxis(type = "category") %>%
      hc_add_series_list(dat)
  })

  output$geo2 <-
    renderTmap({
      tm_shape(data_full_states) + tm_polygons(
        "Pop_density",
        palette = "YlGnBu", breaks = c(0, 20, 50, 100, 150, 200, 400, 600, 800, 1000, 2000, 5000, 10000, 20000, 30000), contrast = 1.1, title = "Population density",
        popup.vars = c(
          "Population density/km2 :" = "Pop_density",
          "Total recovered :" = "Total recovered",
          "New recovered :" = "New recovered",
          "Active cases : " = "Active cases",
          "Serious cases :" = "Serious"
        ), id = "NAME"
      ) +
        tm_scale_bar(breaks = c(0, 25, 50, 75, 100), text.size = 1 / 2) +
        tm_text("countryCode", size = 0.6) +
        tmap_mode("view") + tm_view(set.view = c(7, 51, 2))
    })

  output$geo <-
    renderPlotly({
      fig <- plot_geo(join2) %>%
        add_trace(
          z = ~ get(input$par_M),
          color = input$par_M,
          colors = "#e34a33",
          text = ~ paste(
            Country, "\nSelected parameter:", get(input$par_M),
            "\nNew Cases:", join2$"New cases", "\nTotal Deaths:", join2$"Total deaths",
            "\nCases per 1M:", join2$"Cases/1M", "\nDeaths per 1M:", join2$"Deaths/1M"
          ),
          hoverinfo = "text",
          hoveron = "fill",
          locations = join2$countryCode,
          marker = list(line = country_line_color)
        ) %>%
        colorbar(title = "Color", tickprefix = "") %>%
        layout(
          title = "World map",
          geo = map_options,
          paper_bgcolor = "transparent"
        )
    })

  output$table <- renderGauge({
    gauge(
      input$var,
      min = 0,
      max = max(df$TotalCases[1:6]),
      label = "Total cases",
      gaugeSectors(
        success = c(0, 10000000),
        warning = c(10000001, 20000000),
        danger = c(20000001, 1111500000)
      )
    )
  })

  output$SunBurst <- renderPlotly({
    plot_ly(
      labels = c(
        "Total Cases",
        "Total Recoverd",
        "Total Deaths",
        "New Cases",
        "New Deaths",
        "Active Cases",
        "Serious Cases",
        "Cases per 1M",
        "Deaths per 1M"
      ),
      parents = c(
        "",
        "Total Cases",
        "Total Cases",
        "Total Cases",
        "New Cases",
        "Total Cases",
        "Active Cases",
        "Total Cases",
        "Cases per 1M"
      ),
      values = c(
        sum(join2$"Total cases"[join2$Country == input$var1]),
        sum(join2$"Total recovered"[join2$Country == input$var1]),
        sum(join2$"Total deaths"[join2$Country == input$var1]),
        sum(join2$"New cases"[join2$Country == input$var1]),
        sum(join2$"New deaths"[join2$Country == input$var1]),
        sum(join2$"Active cases"[join2$Country == input$var1]),
        sum(join2$Serious[join2$Country == input$var1]),
        sum(join2$"Cases/1M"[join2$Country == input$var1]),
        sum(join2$"Deaths/1M"[join2$Country == input$var1])
      ),
      type = "sunburst",
      branchvalues = "remainder"
    ) %>% layout(paper_bgcolor = "transparent")
  })

  output$plotDD <- renderHighchart({
    highchart(type = "stock") %>%
      hc_xAxis(type = "datetime") %>%
      hc_add_series(df_url2[, input$var_dd], type = "line", name = paste(input$var_dd)) %>%
      hc_tooltip(DateFormat = "%d,%m,%Y")
  })

  output$vaxx <- renderAmCharts({
    vacc %>%
      subset(vacc$Country == paste(input$vacc_par)) %>%
      amTimeSeries("date", colnames(vacc)[4:ncol(vacc)],
        color = c("#eb3b5a", "#2d98da", "#20bf6b", "#4b6584"),
        type = c(rep("smoothedLine", 2), rep("line", 2)),
        linetype = c(0, 5, 0, 5),
        bullet = c(rep("bubble", 2), rep("round", 2)),
        bulletSize = c(0, 0, 5, 5),
        linewidth = c(4, 4, 1, 1),
        fillAlphas = if (input$fill == TRUE) {
          1
        } else {
          0
        },
        ZoomButton = ZoomButton,
        scrollbar = F
      )
  })

  output$geo3 <-
    renderTmap({
      tm_shape(vaxx_full_geo) + tm_polygons(
        input$vaxx_par,
        palette = "YlGnBu", contrast = 1.1, title = paste(input$vaxx_par),
        popup.vars = c(
          "Selected metric :" = input$vaxx_par
        ), id = "NAME",
        legend.hist = TRUE, n = 9
      ) + tm_layout(legend.outside = TRUE) +
        tm_scale_bar(breaks = c(0, 25, 50, 75, 100), text.size = 1 / 2) +
        tm_text("countryCode", size = 0.6) +
        tmap_mode("view") + tm_view(set.view = c(7, 51, 2))
    })

  output$plotDens <- renderPlotly({
    data_new <- join3
    data_new[, input$response] <- if (isTRUE(input$LogX)) {
      log1p(data_new[input$response])
    } else {
      data_new[, input$response]
    }
    data_new[, input$paraM1] <- if (isTRUE(input$LogY1)) {
      log1p(data_new[, input$paraM1])
    } else {
      data_new[, input$paraM1]
    }
    data_new[, input$paraM2] <- if (isTRUE(input$LogY2)) {
      log1p(data_new[, input$paraM2])
    } else {
      data_new[, input$paraM2]
    }
    ggplotRegression(lm(
      as.formula(paste(
        input$response, "~", input$paraM1, "- Country", "+", input$paraM2
      )),
      # as.formula was used in order to allow drop-down menu for predictor variables
      data = subset(
        data_new,
        get(input$paraM1) != 0 & get(input$paraM2) != 0 &
          get(input$response) != 0 &
          Continent == input$con |
          input$con == "" & get(input$paraM1) != 0 &
            get(input$response) != 0 & get(input$paraM2) != 0
      ) %>%
        filter(
          get(input$paraM1) < input$num &
            get(input$response) < input$num2
        ),
    ))
  })
  output$corrmatrix <- renderPlot({
    ggpairs(join2, columns = c(2:13, 15, 16))
  })
}
```

```{r shinyApp, echo=TRUE, paged.print=TRUE}
shinyApp(ui = ui, server = server)
```

